#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\HomeController::home

login:
    path: /login
    controller: App\Controller\UserController::login

logout:
    path: /logout
    controller: App\Controller\UserController::logout

dashboard:
    path: /dashboard
    controller: App\Controller\BackendController::index

dashboard_posts:
  path: /dashboard/posts
  controller: App\Controller\BackendController::posts

dashboard_account:
  path: /dashboard/account
  controller: App\Controller\BackendController::account

dashboard_create_post:
  path: /dashboard/posts/editor
  controller: App\Controller\PostController::createPost

dashboard_edit_post:
  path: /dashboard/posts/edit/{id}
  controller: App\Controller\PostController::editPost

dashboard_users:
  path: /dashboard/users
  controller: App\Controller\BackendController::users

dashboard_edit_user:
  path: /dashboard/user/edit/{id}
  controller: App\Controller\UserController::edit
  requirements:
    id: '\d+'

user_rename:
  path: /user/rename
  controller: App\Controller\UserController::rename

user_change_password:
  path: /user/changepassword
  controller: App\Controller\UserController::changePassword

registrarse:
    path: /signup
    controller: App\Controller\UserController::signup

post:
  path: /post/{id}
  controller: App\Controller\PostController::post

post_comment:
  path: /post/{id}/comment
  controller: App\Controller\CommentController::commentform
  requirements:
    id: '\d+'

# JsonResponse (para peticiones de ajax)
user_check_username:
  path: /user/checkusername
  controller: App\Controller\UserController::existsUsername
  methods: [POST]

dashboard_delete_post:
  path: /dashboard/posts/delete
  controller: App\Controller\PostController::deletePost
  methods: [POST]

user_delete:
  path: /user/delete/{id}
  controller: App\Controller\UserController::deleteUser
  methods: [GET]
  requirements:
    id: '\d+'

# Api

api_get_users:
  path: /api/user
  controller: App\Controller\Api\UserController::users
  methods: [GET]

api_new_user:
  path: /api/user
  controller: App\Controller\Api\UserController::newUser
  methods: [POST]

api_get_user:
  path: /api/user/{username}
  controller: App\Controller\Api\UserController::getUserByUserName
  methods: [GET]

api_update_user:
  path: /api/user/{username}
  controller: App\Controller\Api\UserController::updateUser
  methods: [PUT]

api_delete_user:
  path: /api/user/{username}
  controller: App\Controller\Api\UserController::deleteUser
  methods: [DELETE]